version: '3'

services:
  snac1:
    image: vacation/snac:latest
    container_name: snac1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./data1:/data
    ports:
      - "8001:8001"  # Map internal port 8000 to external port 8001
    environment:
      - VIRTUAL_HOST=snac1.test
      - VIRTUAL_PORT=8001  # Internal container port for Nginx

  snac2:
    image: vacation/snac:latest
    container_name: snac2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./data2:/data
    ports:
      - "8002:8001"  # Map internal port 8000 to external port 8002
    environment:
      - VIRTUAL_HOST=snac2.test
      - VIRTUAL_PORT=8001  # Internal container port for Nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
