version: '3.9'

services:
  snac1:
    build:
      context: .
      dockerfile: apps/snac1/Dockerfile
    container_name: snac1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./apps/snac1/data:/data
    ports:
      - "8001:8001"  # Map host port 8001 to container port 8001
    environment:
      - VIRTUAL_HOST=snac1.test
      - VIRTUAL_PORT=8001  # Internal container port for Nginx

  snac2:
    build:
      context: .
      dockerfile: apps/snac2/Dockerfile
    container_name: snac2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./apps/snac2/data:/data
    ports:
      - "8002:8001"  # Map host port 8002 to container port 8001
    environment:
      - VIRTUAL_HOST=snac2.test
      - VIRTUAL_PORT=8001  # Internal container port for Nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
