version: '3.9'

services:
  snac1:
    build:
      context: .
      dockerfile: apps/snac1/Dockerfile
    container_name: snac1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./apps/snac1/data:/data
    ports:
      - "8001:8001"
    environment:
      - VIRTUAL_HOST=snac1.test
      - VIRTUAL_PORT=8001
    #dns:
    #  - 127.0.0.11

  ktistec1:
    build:
      context: .
      dockerfile: apps/ktistec1/Dockerfile
    container_name: ktistec1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./apps/ktistec1/data:/db
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=ktistec1.test
      - VIRTUAL_PORT=3000
    #dns:
    #  - 127.0.0.11

  ktistec2:
    build:
      context: .
      dockerfile: apps/ktistec2/Dockerfile
    container_name: ktistec2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./apps/ktistec2/data:/db
    ports:
      - "3001:3000"
    environment:
      - VIRTUAL_HOST=ktistec2.test
      - VIRTUAL_PORT=3000
    #dns:
    #  - 127.0.0.11

  nginx:
    build:
      context: .
      dockerfile: apps/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
      - ./certs:/etc/ssl/private

networks:
  default:
    name: custom-network
